debian/ovmf-install/OVMF_CODE*.fd	/usr/share/pve-edk2-firmware
debian/ovmf-install/OVMF_VARS*.fd	/usr/share/pve-edk2-firmware
debian/ovmf-cvm-install/OVMF_CVM_CODE*.fd	/usr/share/pve-edk2-firmware
debian/ovmf-cvm-install/OVMF_CVM_VARS*.fd	/usr/share/pve-edk2-firmware
debian/ovmf-cvm-install/OVMF_CVM_4M.fd	/usr/share/pve-edk2-firmware
debian/ovmf32-install/OVMF32_CODE*.fd		/usr/share/pve-edk2-firmware
debian/ovmf32-install/OVMF32_VARS*.fd		/usr/share/pve-edk2-firmware
debian/PkKek-1-snakeoil.*			/usr/share/pve-edk2-firmware
